# Keycloak Configuration for Hopital Service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/healthcare-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7070/realms/healthcare-realm/protocol/openid-connect/certs

# Service specific roles
app.security.required-roles.admin=admin,hospital_admin
app.security.required-roles.doctor=doctor,admin
app.security.required-roles.nurse=nurse,doctor,admin
app.security.public-endpoints=/actuator/health,/swagger-ui/**,/v3/api-docs/**
