# Keycloak Configuration for Assurance Service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7070/realms/healthcare-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:7070/realms/healthcare-realm/protocol/openid-connect/certs

# Service specific roles
app.security.required-roles.admin=admin,insurance_agent
app.security.required-roles.insurance=insurance_agent,admin
app.security.required-roles.patient=patient,admin
app.security.public-endpoints=/actuator/health,/swagger-ui/**,/v3/api-docs/**
