spring.application.name=demoApiGateway
server.port=8083

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Route Events
spring.cloud.gateway.routes[0].id=events
spring.cloud.gateway.routes[0].uri=lb://event-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/events/**

# (Optionnel) Discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# (Optionnel) CORS global via Gateway
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*