# ==============================
#   CONFIGURATION EUREKA SERVER
# ==============================

spring.application.name=eureka-server
server.port=8761

# Le serveur Eureka ne s?enregistre pas lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL d?accès (facultatif pour le serveur)
eureka.instance.hostname=localhost

# Si tu veux utiliser le Config Server externe :
spring.config.import=optional:configserver:http://localhost:8888
